aaa_root:
  disabled: true
agents:
- name: KernelFib
  environment_variables:
  - name: KERNELFIB_PROGRAM_ALL_ECMP
    value: '1'
application_traffic_recognition:
  field_sets:
    ipv4_prefixes:
    - name: PFX-PATHFINDERS
  applications:
    ipv4_applications:
    - name: APP-CONTROL-PLANE
      dest_prefix_set_name: PFX-PATHFINDERS
  application_profiles:
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
config_end: true
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9194
  ip_address: 192.168.142.1/32
  flow_tracker:
    hardware: FLOW-TRACKER
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: peerDevice1_Ethernet11
  shutdown: false
  speed: forced 10000full
  channel_group:
    id: 2
    mode: active
  peer: peerDevice1
  peer_interface: Ethernet11
  peer_type: l3_port_channel_member
- name: Ethernet2
  description: peer1
  shutdown: false
  speed: forced 10000full
  channel_group:
    id: 2
    mode: active
  peer: peer1
  peer_type: l3_port_channel_member
- name: Ethernet3
  description: Custom eth3 description
  shutdown: false
  channel_group:
    id: 2
    mode: active
  peer: peer1
  peer_type: l3_port_channel_member
- name: Ethernet1/4
  description: peerDevice2_Ethernet1/12
  shutdown: false
  speed: forced 10000full
  channel_group:
    id: 5
    mode: passive
  peer: peerDevice2
  peer_interface: Ethernet1/12
  peer_type: l3_port_channel_member
- name: Ethernet1/5
  description: peer2
  shutdown: false
  speed: forced 10000full
  channel_group:
    id: 5
    mode: passive
  peer: peer2
  peer_type: l3_port_channel_member
- name: Ethernet1/10
  description: peerDevice3_Ethernet1/10
  shutdown: false
  speed: forced 1000full
  channel_group:
    id: 8
    mode: 'on'
  peer: peerDevice3
  peer_interface: Ethernet1/10
  peer_type: l3_port_channel_member
- name: Ethernet1/19
  description: peerDevice4_Ethernet1/19
  shutdown: true
  channel_group:
    id: 19
    mode: active
  peer: peerDevice4
  peer_interface: Ethernet1/19
  peer_type: l3_port_channel_member
- name: Ethernet1/20
  description: peerDevice4_Ethernet1/20
  shutdown: true
  channel_group:
    id: 19
    mode: active
  peer: peerDevice4
  peer_interface: Ethernet1/20
  peer_type: l3_port_channel_member
flow_tracking:
  hardware:
    trackers:
    - name: FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: node-type-l3-port-channels
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.255.1:511
ip_routing: true
ip_security:
  ike_policies:
  - name: CP-IKE-POLICY
    local_id: 192.168.142.1
  sa_policies:
  - name: DP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  - name: CP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  profiles:
  - name: DP-PROFILE
    sa_policy: DP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890666
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: DP-PROFILE
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_security:
  ssl_profiles:
  - name: STUN-DTLS
    tls_versions: '1.2'
    trust_certificate:
      certificates:
      - aristaDeviceCertProvisionerDefaultRootCA.crt
    certificate:
      file: STUN-DTLS.crt
      key: STUN-DTLS.key
metadata:
  fabric_name: EOS_DESIGNS_UNIT_TESTS
  cv_tags:
    device_tags:
    - name: Role
      value: edge
    - name: Region
      value: AVD_Land_East
    - name: Zone
      value: AVD_Land_East-ZONE
    - name: Site
      value: Site511
    interface_tags:
    - interface: Port-Channel2
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Cybercast
      - name: Circuit
        value: '101'
    - interface: Port-Channel5
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: StreamFast
      - name: Circuit
        value: '102'
    - interface: Port-Channel5.100
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: ExtremeCable
      - name: Circuit
        value: '105'
    - interface: Port-Channel5.105
      tags:
      - name: Type
        value: lan
    - interface: Port-Channel8
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: BlizzardFast
    - interface: Port-Channel19
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: BlizzardFast
  cv_pathfinder:
    role: edge
    region: AVD_Land_East
    zone: AVD_Land_East-ZONE
    site: Site511
    vtep_ip: 192.168.142.1
    ssl_profile: STUN-DTLS
    interfaces:
    - name: Port-Channel2
      carrier: Cybercast
      circuit_id: '101'
      pathgroup: INET
    - name: Port-Channel5
      carrier: StreamFast
      circuit_id: '102'
      pathgroup: INET
    - name: Port-Channel5.100
      carrier: ExtremeCable
      circuit_id: '105'
      pathgroup: INET
    - name: Port-Channel8
      carrier: BlizzardFast
      pathgroup: INET
    - name: Port-Channel19
      carrier: BlizzardFast
      pathgroup: INET
port_channel_interfaces:
- name: Port-Channel2
  description: Cybercast_101_peer1_Port-Channel10
  shutdown: false
  ip_address: 192.168.1.102/31
  service_profile: TEST-QOS-PROFILE1
  flow_tracker:
    hardware: FLOW-TRACKER
  peer: peer1
  peer_interface: Port-Channel10
  peer_type: l3_port_channel
  switchport:
    enabled: false
- name: Port-Channel5
  description: StreamFast_102_peer2_Port-Channel15
  shutdown: false
  service_policy:
    qos:
      input: TEST_POLICY
  ip_address: 192.168.1.105/31
  service_profile: TEST-QOS-PROFILE1
  peer: peer2
  peer_interface: Port-Channel15
  peer_type: l3_port_channel
  switchport:
    enabled: false
  eos_cli: '! TEST RAW_EOS_CLI

    '
- name: Port-Channel5.100
  description: ExtremeCable_105_peer2_Port-Channel15
  shutdown: false
  encapsulation_dot1q:
    vlan: 108
  ip_address: 192.168.100.115/31
  service_profile: TEST-QOS-PROFILE2
  flow_tracker:
    hardware: FLOW-TRACKER
  peer: peer2
  peer_interface: Port-Channel15
  peer_type: l3_port_channel
- name: Port-Channel5.105
  description: peer2_Port-Channel16
  shutdown: false
  encapsulation_dot1q:
    vlan: 105
  ip_address: 192.168.100.116/31
  service_profile: TEST-QOS-PROFILE2
  flow_tracker:
    hardware: FLOW-TRACKER
  peer: peer2
  peer_interface: Port-Channel16
  peer_type: l3_port_channel
- name: Port-Channel8
  description: BlizzardFast_peerDevice3_Port-Channel18
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  service_profile: TEST-QOS-PROFILE3
  flow_tracker:
    hardware: FLOW-TRACKER
  peer: peerDevice3
  peer_interface: Port-Channel18
  peer_type: l3_port_channel
  switchport:
    enabled: false
  eos_cli: '! TEST RAW_EOS_CLI 123

    '
- name: Port-Channel19
  description: BlizzardFast_peerDevice4_Port-Channel20
  shutdown: true
  ip_address: 192.168.1.19/31
  peer: peerDevice4
  peer_interface: Port-Channel20
  peer_type: l3_port_channel
  switchport:
    enabled: false
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 192.168.255.1:511 additive
- name: RM-EVPN-SOO-IN
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - extcommunity soo 192.168.255.1:511 additive
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
router_adaptive_virtual_topology:
  topology_role: edge
  region:
    name: AVD_Land_East
    id: 43
  zone:
    name: AVD_Land_East-ZONE
    id: 1
  site:
    name: Site511
    id: 511
  profiles:
  - name: DEFAULT-POLICY-CONTROL-PLANE
    load_balance_policy: LB-DEFAULT-POLICY-CONTROL-PLANE
  - name: DEFAULT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-POLICY-DEFAULT
  policies:
  - name: DEFAULT-POLICY-WITH-CP
    matches:
    - application_profile: APP-PROFILE-CONTROL-PLANE
      avt_profile: DEFAULT-POLICY-CONTROL-PLANE
    - application_profile: default
      avt_profile: DEFAULT-POLICY-DEFAULT
  vrfs:
  - name: default
    policy: DEFAULT-POLICY-WITH-CP
    profiles:
    - name: DEFAULT-POLICY-CONTROL-PLANE
      id: 254
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65005'
  router_id: 192.168.255.1
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    remote_as: '65005'
    update_source: Dps1
    bfd: true
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    ttl_maximum_hops: 1
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      route_map_in: RM-EVPN-SOO-IN
      route_map_out: RM-EVPN-SOO-OUT
      encapsulation: path-selection
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    path_selection:
      roles:
        producer: true
  address_family_path_selection:
    bgp:
      additional_paths:
        receive: true
        send: any
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  vrfs:
  - name: default
    rd: 192.168.255.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
router_path_selection:
  path_groups:
  - name: INET
    id: 101
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Port-Channel2
    - name: Port-Channel5
    - name: Port-Channel5.100
    - name: Port-Channel8
    - name: Port-Channel19
    dynamic_peers:
      enabled: true
  load_balance_policies:
  - name: LB-DEFAULT-POLICY-CONTROL-PLANE
    path_groups:
    - name: INET
  - name: LB-DEFAULT-POLICY-DEFAULT
    path_groups:
    - name: INET
  tcp_mss_ceiling:
    ipv4_segment_size: auto
router_traffic_engineering:
  enabled: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.103
transceiver_qsfp_default_mode_4x10: false
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: node-type-l3-port-channels_VTEP
    vxlan:
      source_interface: Dps1
      udp_port: 4789
      vrfs:
      - name: default
        vni: 1
